"""add_article_detail_fields

Revision ID: 2699e0dcfa9f
Revises: 9f8b44ce59af
Create Date: 2026-03-26 15:01:24.160886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2699e0dcfa9f'
down_revision: Union[str, None] = '9f8b44ce59af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key_hash', sa.String(length=128), nullable=False),
    sa.Column('client_name', sa.String(length=100), nullable=False),
    sa.Column('permissions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_used', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_api_keys_is_active', 'api_keys', ['is_active'], unique=False)
    op.create_index('ix_api_keys_key_hash', 'api_keys', ['key_hash'], unique=False)
    op.add_column('events', sa.Column('translated_title', sa.String(length=500), nullable=True))
    op.add_column('events', sa.Column('translated_description', sa.Text(), nullable=True))
    op.add_column('events', sa.Column('is_translated', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('events', sa.Column('cargo_type', sa.String(length=100), nullable=True))
    op.add_column('events', sa.Column('modus_operandi', sa.String(length=200), nullable=True))
    op.add_column('events', sa.Column('location_detail', sa.String(length=500), nullable=True))
    op.add_column('events', sa.Column('vehicle_country', sa.String(length=5), nullable=True))
    op.add_column('events', sa.Column('intelligence_tier', sa.Integer(), nullable=True))
    op.add_column('events', sa.Column('intelligence_category', sa.String(length=50), nullable=True))
    op.add_column('events', sa.Column('intelligence_confidence', sa.Float(), nullable=True))
    op.create_index('ix_events_intelligence_tier', 'events', ['intelligence_tier'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_events_intelligence_tier', table_name='events')
    op.drop_column('events', 'intelligence_confidence')
    op.drop_column('events', 'intelligence_category')
    op.drop_column('events', 'intelligence_tier')
    op.drop_column('events', 'vehicle_country')
    op.drop_column('events', 'location_detail')
    op.drop_column('events', 'modus_operandi')
    op.drop_column('events', 'cargo_type')
    op.drop_column('events', 'is_translated')
    op.drop_column('events', 'translated_description')
    op.drop_column('events', 'translated_title')
    op.drop_index('ix_api_keys_key_hash', table_name='api_keys')
    op.drop_index('ix_api_keys_is_active', table_name='api_keys')
    op.drop_table('api_keys')
    # ### end Alembic commands ###
