"""initial_schema

Revision ID: 4cdd1602b2dc
Revises: 
Create Date: 2026-03-24 11:59:28.229413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4cdd1602b2dc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_statuses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('agent_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('last_heartbeat', sa.DateTime(), nullable=True),
    sa.Column('events_collected_today', sa.Integer(), nullable=False),
    sa.Column('errors_today', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('uptime_seconds', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_agent_statuses_country_agent', 'agent_statuses', ['country_code', 'agent_type'], unique=True)
    op.create_index('ix_agent_statuses_country_code', 'agent_statuses', ['country_code'], unique=False)
    op.create_index('ix_agent_statuses_status', 'agent_statuses', ['status'], unique=False)
    op.create_table('companies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('company_type', sa.String(length=50), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('region', sa.String(length=200), nullable=True),
    sa.Column('registration_number', sa.String(length=100), nullable=True),
    sa.Column('tax_id', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('financial_status', sa.String(length=50), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('first_seen', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_updated', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('source_type', sa.String(length=50), nullable=True),
    sa.Column('is_from_official_source', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_companies_country_code', 'companies', ['country_code'], unique=False)
    op.create_index('ix_companies_financial_status', 'companies', ['financial_status'], unique=False)
    op.create_index('ix_companies_name', 'companies', ['name'], unique=False)
    op.create_table('crime_hotspots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('region', sa.String(length=200), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('radius_km', sa.Float(), nullable=False),
    sa.Column('hotspot_type', sa.String(length=50), nullable=False),
    sa.Column('event_count', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('peak_hours', sa.String(length=50), nullable=True),
    sa.Column('common_targets', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('trend', sa.String(length=20), nullable=False),
    sa.Column('last_calculated', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_crime_hotspots_country_code', 'crime_hotspots', ['country_code'], unique=False)
    op.create_index('ix_crime_hotspots_hotspot_type', 'crime_hotspots', ['hotspot_type'], unique=False)
    op.create_index('ix_crime_hotspots_severity', 'crime_hotspots', ['severity'], unique=False)
    op.create_table('event_correlations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('correlation_type', sa.String(length=50), nullable=False),
    sa.Column('event_ids', postgresql.ARRAY(sa.UUID()), nullable=True),
    sa.Column('company_ids', postgresql.ARRAY(sa.UUID()), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('country_codes', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('pattern_description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('detected_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_event_correlations_correlation_type', 'event_correlations', ['correlation_type'], unique=False)
    op.create_index('ix_event_correlations_is_active', 'event_correlations', ['is_active'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('report_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('countries', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('language', sa.String(length=5), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('file_path', sa.String(length=1000), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('total_events', sa.Integer(), nullable=False),
    sa.Column('confirmed_events', sa.Integer(), nullable=False),
    sa.Column('signal_events', sa.Integer(), nullable=False),
    sa.Column('disclaimer_text', sa.Text(), nullable=True),
    sa.Column('generated_by', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_reports_report_type', 'reports', ['report_type'], unique=False)
    op.create_index('ix_reports_status', 'reports', ['status'], unique=False)
    op.create_table('sources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('url', sa.String(length=2000), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('trust_score', sa.Float(), nullable=False),
    sa.Column('is_official', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_scraped', sa.DateTime(), nullable=True),
    sa.Column('scrape_interval_minutes', sa.Integer(), nullable=False),
    sa.Column('total_events_collected', sa.Integer(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sources_country_code', 'sources', ['country_code'], unique=False)
    op.create_index('ix_sources_source_type', 'sources', ['source_type'], unique=False)
    op.create_table('subscribers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_name', sa.String(length=500), nullable=False),
    sa.Column('contact_email', sa.String(length=300), nullable=False),
    sa.Column('subscription_tier', sa.String(length=50), nullable=False),
    sa.Column('subscribed_countries', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('language_preference', sa.String(length=5), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('subscription_start', sa.Date(), nullable=False),
    sa.Column('subscription_end', sa.Date(), nullable=True),
    sa.Column('monthly_fee_eur', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_subscribers_is_active', 'subscribers', ['is_active'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('alert_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('country_codes', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('region', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('triggered_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('related_event_ids', postgresql.ARRAY(sa.UUID()), nullable=True),
    sa.Column('related_company_id', sa.UUID(), nullable=True),
    sa.Column('notification_sent', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['related_company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_alerts_alert_type', 'alerts', ['alert_type'], unique=False)
    op.create_index('ix_alerts_is_active', 'alerts', ['is_active'], unique=False)
    op.create_index('ix_alerts_severity', 'alerts', ['severity'], unique=False)
    op.create_table('company_financials',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('date_occurred', sa.Date(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('source_url', sa.String(length=2000), nullable=True),
    sa.Column('amount_eur', sa.Float(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_company_financials_company_id', 'company_financials', ['company_id'], unique=False)
    op.create_index('ix_company_financials_event_type', 'company_financials', ['event_type'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('date_occurred', sa.DateTime(), nullable=True),
    sa.Column('date_collected', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('region', sa.String(length=200), nullable=True),
    sa.Column('city', sa.String(length=200), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('trust_score', sa.Float(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_anonymized', sa.Boolean(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('processed_text', sa.Text(), nullable=True),
    sa.Column('source_url', sa.String(length=2000), nullable=True),
    sa.Column('language', sa.String(length=5), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('financial_impact_eur', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_events_company_id', 'events', ['company_id'], unique=False)
    op.create_index('ix_events_country_code', 'events', ['country_code'], unique=False)
    op.create_index('ix_events_date_occurred', 'events', ['date_occurred'], unique=False)
    op.create_index('ix_events_event_type', 'events', ['event_type'], unique=False)
    op.create_index('ix_events_severity', 'events', ['severity'], unique=False)
    op.create_index('ix_events_source_id', 'events', ['source_id'], unique=False)
    op.create_index('ix_events_trust_score', 'events', ['trust_score'], unique=False)
    op.create_table('audit_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('original_data_hash', sa.String(length=64), nullable=True),
    sa.Column('processed_by', sa.String(length=100), nullable=True),
    sa.Column('country_code', sa.String(length=2), nullable=True),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_log_action', 'audit_log', ['action'], unique=False)
    op.create_index('ix_audit_log_event_id', 'audit_log', ['event_id'], unique=False)
    op.create_index('ix_audit_log_timestamp', 'audit_log', ['timestamp'], unique=False)
    op.create_table('legal_reviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('reason', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reviewer_notes', sa.Text(), nullable=True),
    sa.Column('reviewed_by', sa.String(length=100), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('auto_resolved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_legal_reviews_event_id', 'legal_reviews', ['event_id'], unique=False)
    op.create_index('ix_legal_reviews_status', 'legal_reviews', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_legal_reviews_status', table_name='legal_reviews')
    op.drop_index('ix_legal_reviews_event_id', table_name='legal_reviews')
    op.drop_table('legal_reviews')
    op.drop_index('ix_audit_log_timestamp', table_name='audit_log')
    op.drop_index('ix_audit_log_event_id', table_name='audit_log')
    op.drop_index('ix_audit_log_action', table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index('ix_events_trust_score', table_name='events')
    op.drop_index('ix_events_source_id', table_name='events')
    op.drop_index('ix_events_severity', table_name='events')
    op.drop_index('ix_events_event_type', table_name='events')
    op.drop_index('ix_events_date_occurred', table_name='events')
    op.drop_index('ix_events_country_code', table_name='events')
    op.drop_index('ix_events_company_id', table_name='events')
    op.drop_table('events')
    op.drop_index('ix_company_financials_event_type', table_name='company_financials')
    op.drop_index('ix_company_financials_company_id', table_name='company_financials')
    op.drop_table('company_financials')
    op.drop_index('ix_alerts_severity', table_name='alerts')
    op.drop_index('ix_alerts_is_active', table_name='alerts')
    op.drop_index('ix_alerts_alert_type', table_name='alerts')
    op.drop_table('alerts')
    op.drop_index('ix_subscribers_is_active', table_name='subscribers')
    op.drop_table('subscribers')
    op.drop_index('ix_sources_source_type', table_name='sources')
    op.drop_index('ix_sources_country_code', table_name='sources')
    op.drop_table('sources')
    op.drop_index('ix_reports_status', table_name='reports')
    op.drop_index('ix_reports_report_type', table_name='reports')
    op.drop_table('reports')
    op.drop_index('ix_event_correlations_is_active', table_name='event_correlations')
    op.drop_index('ix_event_correlations_correlation_type', table_name='event_correlations')
    op.drop_table('event_correlations')
    op.drop_index('ix_crime_hotspots_severity', table_name='crime_hotspots')
    op.drop_index('ix_crime_hotspots_hotspot_type', table_name='crime_hotspots')
    op.drop_index('ix_crime_hotspots_country_code', table_name='crime_hotspots')
    op.drop_table('crime_hotspots')
    op.drop_index('ix_companies_name', table_name='companies')
    op.drop_index('ix_companies_financial_status', table_name='companies')
    op.drop_index('ix_companies_country_code', table_name='companies')
    op.drop_table('companies')
    op.drop_index('ix_agent_statuses_status', table_name='agent_statuses')
    op.drop_index('ix_agent_statuses_country_code', table_name='agent_statuses')
    op.drop_index('ix_agent_statuses_country_agent', table_name='agent_statuses')
    op.drop_table('agent_statuses')
    # ### end Alembic commands ###
